# Generated by Django 6.1 on 2026-08-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)')], default='ARS', max_length=3)),
                ('condicion', models.CharField(choices=[('0km', '0km'), ('usado', 'Usado')], max_length=10)),
                ('kilometraje', models.PositiveIntegerField(blank=True, help_text='Dejar vacío si es 0km', null=True)),
                ('combustible', models.CharField(blank=True, max_length=30)),
                ('transmision', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar del catálogo sin borrar')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='autos.auto')),
            ],
        ),
        migrations.CreateModel(
            name='FotoAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='autos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='autos.auto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
